These tests were written using Diffblue Cover.
Diffblue-benchmarks/Gephi-gephi pull request #1
Opened 2019-08-06 12:38 UTC by ThomasPerkins1123

2019-08-06 13:28 UTC, petersear requested changes
The PR title could contain the (unqualified) class names.
The commit message only contains the `These tests were written using Diffblue Cover.` line and nothing about the tests being added.

2019-08-06 13:28 UTC, petersear commented on modules/ProjectAPI/src/test/java/org/gephi/project/io/XMLCharTest.java
> +	public void isValidInputPositiveOutputFalse() {
Either make this into two tests (true and false) or rename the test to something like `testIsValid()`
Currently, the name contains `False` but both true and false outcomes are expected.

2019-08-06 13:28 UTC, petersear commented on modules/Utils/src/test/java/org/gephi/utils/HTMLEscapeTest.java
> +	@Test
Add blank line before `@Test`

2019-08-08 11:03 UTC, petersear reviewed
@ThomasPerkins1123 Did you see my previous comments about the commit text and PR title?

2019-08-08 16:19 UTC, ThomasPerkins1123 commented
> @ThomasPerkins1123 Did you see my previous comments about the commit text and PR title?

@petersear Sorry I  missed that! Fixed now

2019-08-08 16:23 UTC, petersear approved these changes

2019-08-09 08:14 UTC, paulkennethkent approved these changes

2019-09-03 16:19 UTC, closed without merging